name: NLP ML API Tests

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    strategy:
      matrix:
        python-version: [ "3.10" ]
        poetry-version: [ "1.1.13" ]

    name: test
    runs-on: ubuntu-latest

    steps:
      - name: Check out PR branch
        uses: actions/checkout@v3

      - name: Setup Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pip and poetry ${{ matrix.poetry-version }}
        run: |
          python -m pip install --upgrade pip
          pip install poetry==${{ matrix.poetry-version }}

      - name: Install Dependencies
        with:
          cache: 'poetry'
        run: |
          cd ./mlapi/mlapi
          poetry install --no-interaction --no-root

      - name: Pytest
        run: |
          cd ./mlapi/mlapi
          poetry run pytest -vv
